Moved to asyncio
kadircancetin/MostMinimalWebFramework pull request #2
Opened 2022-07-06 10:42 UTC by mihett05

Using asyncio sockets instead of sockets
JSONResponse became jsonify function
ApiException has content-type: application/json

2022-07-06 21:41 UTC, kadircancetin requested changes
I really like it. I mean, I really, really like it. But I have doubts to move it to asyncio. 

1) I think people like it because it looks very easy and understandable. Moving it to `asyncio` makes it a little hard to understandable.
2) But It makes code more performant and featureful.

Performance in  🟡 (Meh) category, for personal use in 🟡 (Meh) category, and featureful is in ⭕ (NO) category.
But readably in 🟢 (IMPORTANT) category.

So huge increase of   🟡 (Meh), 🟡 (Meh) and  ⭕ (NO), but little decrease of 🟢 (IMPORTANT).

I think I will merge it. I just have little doubts. What do you think?

2022-07-06 21:41 UTC, kadircancetin commented on MostMinimalWebFramework.py
> +    return Response(content_type="application/json", *args, **kwargs)
Sorry, I don't like the idea of Response is class and Json response is function. IMHO, It decreases readability of implemented views.

2022-07-06 21:41 UTC, kadircancetin commented on MostMinimalWebFramework.py
> -
I don't know why I do this. Thanks :rocket:

2022-07-07 09:50 UTC, mihett05 commented on MostMinimalWebFramework.py
> +    return Response(content_type="application/json", *args, **kwargs)
Fair enough, returned it as a class

2022-07-07 10:10 UTC, mihett05 commented
> What do you think about decreasing the readiblity?

I think there isn't a decrease of the readability, because here I'm using high-level asyncio api instead of manual creating socket server and now there is only request handling logic instead of connection and requests logic.

2022-07-07 10:12 UTC, mihett05 reviewed
> What do you think about decreasing the readiblity?

I think there isn't a decrease of the readability, because here I'm using high-level asyncio api instead of manual creating socket server and now there is only request handling logic instead of connection and requests logic.

2025-02-03 15:36 UTC, merged